#!/bin/bash
# generate-inventory.sh — generates inventory/hosts.ini from Terraform output.
#
# Run this every time you do a fresh `terraform apply` since the EC2 IP
# may change. hosts.ini is git-ignored so it never gets committed stale.
#
# Usage (from the ansible/ directory):
#   ./inventory/generate-inventory.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TERRAFORM_DIR="$(cd "${SCRIPT_DIR}/../../terraform/environments/dev" && pwd)"
INVENTORY_FILE="${SCRIPT_DIR}/hosts.ini"

echo "Reading Terraform output from: ${TERRAFORM_DIR}"

# Pull the Elastic IP from Terraform output.
# Requires: terraform must have been applied and state must exist.
INSTANCE_IP=$(terraform -chdir="${TERRAFORM_DIR}" output -raw vpn_public_ip 2>/dev/null)

if [[ -z "${INSTANCE_IP}" ]]; then
  echo "ERROR: Could not get instance_public_ip from Terraform output."
  echo "Make sure you have run 'terraform apply' in ${TERRAFORM_DIR} first."
  exit 1
fi

echo "EC2 IP: ${INSTANCE_IP}"

# Write the inventory file
cat > "${INVENTORY_FILE}" << EOF
# Auto-generated by generate-inventory.sh — do not edit manually.
# Re-run the script after every terraform apply.
[vpn]
trusttunnel ansible_host=${INSTANCE_IP}

[vpn:vars]
ansible_user=ubuntu
EOF

echo "Inventory written to: ${INVENTORY_FILE}"
